# Generated by Django 6.0.3 on 2026-03-10 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiendpoint',
            options={'verbose_name_plural': 'api_end_point'},
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('success', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.apiendpoint')),
            ],
        ),
    ]
