# Generated by Django 6.0.3 on 2026-03-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_apiendpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthlog',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitor.apiendpoint'),
        ),
    ]
