# Generated by Django 6.0.3 on 2026-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_healthlog_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
