# Generated by Django 6.0.3 on 2026-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_apiendpoint_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='latency_threshold',
            field=models.FloatField(default=2.0),
        ),
    ]
