# Generated by Django 6.0.3 on 2026-03-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_apiendpoint_latency_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
