# Generated by Django 6.0.3 on 2026-04-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_apiendpoint_last_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='keep_alive',
            field=models.BooleanField(default=True),
        ),
    ]
