# Generated by Django 6.0.3 on 2026-04-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_apiendpoint_keep_alive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthlog',
            index=models.Index(fields=['api', '-checked_at'], name='monitor_hea_api_id_3672f0_idx'),
        ),
        migrations.AddIndex(
            model_name='healthlog',
            index=models.Index(fields=['checked_at'], name='monitor_hea_checked_5fef15_idx'),
        ),
    ]
